### ISSUE TITLE
lol

### ISSUE THREAD

**Issue by hadim** [opoirion/pres_ml#1]
victime

**Comment by hadim** [comment]
https://github.com/hadim/revealjs-template

**Comment by hadim** [comment]
https://github.com/hadim/phd_thesis

**Comment by hadim** [comment]
@opoirion

**Comment by hadim** [comment]
lol tu met des titres à tes commits :-D

**Comment by opoirion** [comment]
victime, j'ai essaye d'ouvrir ta these ds mon navigateur sa a fait planté
mon pc^^

2015-11-26 18:12 GMT+01:00 Hadrien Mary notifications@github.com:

> lol tu met des titres à tes commits :-D
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/opoirion/pres_ml/issues/1#issuecomment-159961888.

## 

Olivier Poirion
o.poirion@gmail.com
olivier.poirion@ec-lyon.fr
mobile: +336 3249 3666

**Comment by opoirion** [comment]
je suis sur que ta passé plus de tps a configuré ta lib de crotte que de
trouver d resultats crédible

2015-11-26 18:32 GMT+01:00 olivier poirion o.poirion@gmail.com:

> victime, j'ai essaye d'ouvrir ta these ds mon navigateur sa a fait planté
> mon pc^^
> 
> 2015-11-26 18:12 GMT+01:00 Hadrien Mary notifications@github.com:
> 
> > lol tu met des titres à tes commits :-D
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/opoirion/pres_ml/issues/1#issuecomment-159961888.
> 
> ## 
> 
> Olivier Poirion
> o.poirion@gmail.com
> olivier.poirion@ec-lyon.fr
> mobile: +336 3249 3666

## 

Olivier Poirion
o.poirion@gmail.com
olivier.poirion@ec-lyon.fr
mobile: +336 3249 3666

**Comment by hadim** [comment]
bah non moi je sais me servir d'un PC :-)

**Comment by opoirion** [comment]
bon je suis pas allé au bou de lintro ct trop relou^^

2015-11-26 18:34 GMT+01:00 Hadrien Mary notifications@github.com:

> bah non moi je sais me servir d'un PC :-)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/opoirion/pres_ml/issues/1#issuecomment-159964984.

## 

Olivier Poirion
o.poirion@gmail.com
olivier.poirion@ec-lyon.fr
mobile: +336 3249 3666

**Comment by hadim** [comment]
t'as raison, j'aurais fait pareil... je peux plus la voir cette thèse.

**Comment by hadim** [comment]
allez bisous victime, j'ai poker

**Comment by opoirion** [comment]
par contre tes remerciments c trop en mode victime !!

Le 26 novembre 2015 18:38, Hadrien Mary notifications@github.com a écrit :

> t'as raison, j'aurais fait pareil... je peux plus la voir cette thèse.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/opoirion/pres_ml/issues/1#issuecomment-159965468.

## 

Olivier Poirion
o.poirion@gmail.com
olivier.poirion@ec-lyon.fr
mobile: +336 3249 3666
